### ISSUE TITLE
Bug Error Exists

### ISSUE THREAD

**Issue by alitheDev** [abbas0v/php_multi-user_login#1]
when i connect its shows:

_Parse error: syntax error, unexpected 'public' (T_PUBLIC) in E:\FYP DRIVE\Xampp Software\Xampp\htdocs\SoftwareAreHere\mini modules\php multiuser login\php_multi-user_login-master\includes\functions.php on line 29_

**Comment by vikash6932** [comment]
Parse error: syntax error, unexpected 'public' (T_PUBLIC) in D:\xampp\htdocs\testing\multi-user\includes\functions.php on line 29

Please Admin Help Me,

**Comment by abbas0v** [comment]
Hi guys. I fixed this bug after 2 years :D Sorry I'm too busy. Have a good day ☕

**Comment by abbas0v** [comment]
Hi guys. I fixed this bug after 2 years :D Sorry I'm too busy. Have a good day ☕

**Comment by wowels** [comment]
Hi when we close the user logged in tab and reopen to access the home index page I got an error message

Warning: Undefined array key "login" in C:\xampp\htdocs\multiuser\includes\functions.php on line 39

Fatal error: Uncaught TypeError: mysqli_query(): Argument #1 ($mysql) must be of type mysqli, null given in C:\xampp\htdocs\multiuser\includes\functions.php:42 Stack trace: #0 C:\xampp\htdocs\multiuser\includes\functions.php(42): mysqli_query(NULL, 'SELECT * FROM u...') #1 C:\xampp\htdocs\multiuser\includes\checkuser.php(4): Login->SessionCheck() #2 {main} thrown in C:\xampp\htdocs\multiuser\includes\functions.php on line 42
